In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\ASUS\skripsi\df_preprocessed.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10569 entries, 0 to 10568
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           10569 non-null  object
 1   link           10569 non-null  object
 2   username       10569 non-null  object
 3   tweet          10569 non-null  object
 4   like           10569 non-null  int64
 5   retweet        10569 non-null  int64
 6   reply          10569 non-null  int64
 7   qrt            10569 non-null  int64
 8   cleansing      10556 non-null  object
 9   normalization  10556 non-null  object
 10  stemmed        10556 non-null  object
 11  tokenized      10569 non-null  object
 12  filtered       10569 non-null  object
 13  preprocessed   10556 non-null  object
dtypes: int64(4), object(10)
memory usage: 1.1+ MB

In [6]:
df[df['preprocessed'].isna()]

,date,link,username,tweet,like,retweet,reply,qrt,cleansing,normalization,stemmed,tokenized,filtered,preprocessed
528,2021-12-03 15:54:30,https://twitter.com/86msib/status/146679800258...,86msib,#wolfkat #weekendvibes #familytime #instagood ...,1,0,0,0,NaN,NaN,NaN,[''],[''],NaN
531,2021-12-03 15:31:37,https://twitter.com/86msib/status/146679224590...,86msib,#bosphorus # #wolfkat #weekendvibes #familytim...,2,0,0,0,NaN,NaN,NaN,[''],[''],NaN
532,2021-12-03 15:27:06,https://twitter.com/86msib/status/146679110954...,86msib,#bosphorus # #wolfkat #weekendvibes #familytim...,2,0,0,0,NaN,NaN,NaN,[''],[''],NaN
533,2021-12-03 13:57:51,https://twitter.com/86msib/status/146676864557...,86msib,#hoteltropicaldaisy #wolfkat #weekendvibes #fa...,1,0,0,0,NaN,NaN,NaN,[''],[''],NaN
534,2021-12-03 13:56:42,https://twitter.com/86msib/status/146676835964...,86msib,#hoteltropicaldaisy #wolfkat #weekendvibes #fa...,1,0,0,0,NaN,NaN,NaN,[''],[''],NaN
1147,2022-03-27 20:24:14,https://twitter.com/g_msib/status/150817810130...,g_msib,@AnfisaElshina @iLiverbird Кто-то неправильно ...,0,0,0,0,NaN,NaN,NaN,[''],[''],NaN
1495,2022-06-28 23:17:26,https://twitter.com/krmhh17/status/15419237587...,krmhh17,[𝘼 𝙏𝙝𝙧𝙚𝙖𝙙 — 𝙎𝙝𝙖𝙧𝙞𝙣𝙜 𝙋𝙚𝙣𝙜𝙖𝙡𝙖𝙢𝙖𝙣 𝙎𝙚𝙥𝙪𝙩𝙖𝙧 𝙈𝙖𝙜𝙖𝙣𝙜 ...,66,12,5,1,NaN,NaN,NaN,[''],[''],NaN
2233,2022-07-20 14:46:22,https://twitter.com/widyarobotics/status/15497...,widyarobotics,#msib #kampusmerdeka #nadiemmakarim #intern #m...,0,0,0,0,NaN,NaN,NaN,[''],[''],NaN
4850,2022-12-23 04:51:02,https://twitter.com/putulino/status/1606150366...,putulino,#berprosesmeraihsukses #MagangMerdeka #KampusM...,2,0,0,0,NaN,NaN,NaN,[''],[''],NaN
5518,2022-12-01 03:30:54,https://twitter.com/tpp_msib3/status/159815766...,tpp_msib3,#kampusmerdeka⁣\n#msib⁣\n#batch3⁣\n#pttpp⁣\n#t...,0,0,0,0,NaN,NaN,NaN,[''],[''],NaN
8732,2023-02-27 05:24:06,https://twitter.com/KementerianESDM/status/163...,KementerianESDM,#KitaGerilya\n#MagangBersertifikat\n#MSIB\n#En...,0,0,0,0,NaN,NaN,NaN,[''],[''],NaN
8894,2023-02-20 09:54:56,https://twitter.com/PPSDM_ATRBPN/status/162760...,PPSDM_ATRBPN,#MSIB #MBKM #TuntasdanBangkit #MenujuLayananBe...,0,0,0,0,NaN,NaN,NaN,[''],[''],NaN
10471,2023-02-01 12:39:08,https://twitter.com/Saniyaoldmoney/status/1620...,Saniyaoldmoney,#mbkm #msib #magangmerdeka,0,0,0,0,NaN,NaN,NaN,[''],[''],NaN